# Generated by Django 5.0 on 2023-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=100)),
                ("empnumber", models.CharField(max_length=100)),
                ("salary", models.CharField(max_length=100)),
                ("experiance", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("pastexp", models.BooleanField()),
                ("prevjoin", models.CharField(max_length=100)),
                ("prevleave", models.CharField(max_length=100)),
            ],
        ),
    ]
